import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { test, type TestContext } from "node:test";
import { parse, type ParseError } from "jsonc-parser";
import YAML from "yaml";
import {
  createSandbox,
  hashFile,
  realOpenCodeFiles,
  runCli,
  snapshotFiles,
  type CliResult,
  type Sandbox,
} from "../helpers/sandbox.js";

const PROJECT_START = "<!-- agenthome:project:start -->";
const PROJECT_END = "<!-- agenthome:project:end -->";
const MANAGED_MARKER = "@agenthome-managed";
const MANAGED_HEADER = [
  `// ${MANAGED_MARKER}`,
  "// Generated by AgentHome. Manual edits to this file may be overwritten.",
];

/** Fresh sandbox; asserts the real OpenCode config is byte-identical when the test ends. */
async function makeSandbox(t: TestContext): Promise<Sandbox> {
  const realBefore = await snapshotFiles(realOpenCodeFiles());
  const sandbox = await createSandbox();
  t.after(async () => {
    await sandbox.cleanup();
    const realAfter = await snapshotFiles(realOpenCodeFiles());
    assert.deepEqual(realAfter, realBefore, "test touched the real OpenCode configuration");
  });
  return sandbox;
}

/** CLI invocation with explicit --home/--project; cwd is already the sandbox project. */
function cli(sandbox: Sandbox, args: string[]): Promise<CliResult> {
  return runCli([...args, "--home", sandbox.home, "--project", sandbox.project], sandbox);
}

async function initSandbox(sandbox: Sandbox): Promise<void> {
  const result = await cli(sandbox, ["init"]);
  assert.equal(result.code, 0, result.stderr);
}

async function mustExist(file: string): Promise<void> {
  assert.notEqual(await hashFile(file), null, `expected file to exist: ${file}`);
}

function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

async function readJsonc(file: string): Promise<Record<string, unknown>> {
  const errors: ParseError[] = [];
  const parsed = parse(await fs.readFile(file, "utf8"), errors, {
    allowTrailingComma: true,
    disallowComments: false,
  });
  assert.equal(errors.length, 0, `expected valid JSONC: ${file}`);
  return parsed as Record<string, unknown>;
}

async function readYaml(file: string): Promise<Record<string, unknown>> {
  return YAML.parse(await fs.readFile(file, "utf8")) as Record<string, unknown>;
}

function globalFiles(sandbox: Sandbox): { registry: string; providers: string } {
  return {
    registry: path.join(sandbox.home, ".agenthome", "mcp", "registry.yaml"),
    providers: path.join(sandbox.home, ".agenthome", "providers", "providers.yaml"),
  };
}

test("init creates global and project AgentHome files", async (t) => {
  const sandbox = await makeSandbox(t);
  const result = await cli(sandbox, ["init"]);
  assert.equal(result.code, 0, result.stderr);

  const expected = [
    path.join(sandbox.home, ".agenthome", "agenthome.yaml"),
    path.join(sandbox.home, ".agenthome", "memory", "global.md"),
    path.join(sandbox.home, ".agenthome", "rules", "global.md"),
    path.join(sandbox.home, ".agenthome", "mcp", "registry.yaml"),
    path.join(sandbox.home, ".agenthome", "providers", "providers.yaml"),
    path.join(sandbox.project, ".agenthome.yaml"),
    path.join(sandbox.project, ".agenthome", "memory.md"),
    path.join(sandbox.project, ".agenthome", "rules.md"),
    path.join(sandbox.project, ".agenthome", "mcp.yaml"),
  ];
  for (const file of expected) await mustExist(file);
  assert.doesNotMatch(result.stdout, /First-installation adoption/);

  const globalConfig = await readYaml(path.join(sandbox.home, ".agenthome", "agenthome.yaml"));
  assert.equal(globalConfig.mcpRegistry, "~/.agenthome/mcp/registry.yaml");
  const projectConfig = await readYaml(path.join(sandbox.project, ".agenthome.yaml"));
  assert.equal(projectConfig.mcpRegistry, "./.agenthome/mcp.yaml");
});

test("init adopts the user's global mcp servers and model on first installation", async (t) => {
  const sandbox = await makeSandbox(t);
  const userFile = path.join(sandbox.home, ".config", "opencode", "opencode.json");
  await fs.mkdir(path.dirname(userFile), { recursive: true });
  await fs.writeFile(
    userFile,
    `${JSON.stringify(
      {
        model: "prov/id",
        mcp: {
          localone: { type: "local", command: ["node", "server.js"] },
          remoteone: { type: "remote", url: "https://example.com/mcp", enabled: true },
        },
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
  const userHash = await hashFile(userFile);

  const result = await cli(sandbox, ["init"]);
  assert.equal(result.code, 0, result.stderr);
  assert.match(result.stdout, /First-installation adoption:/);
  assert.match(result.stdout, /mcp adopted: localone, remoteone/);
  assert.match(result.stdout, /model adopted: prov\/id/);

  const { registry, providers } = globalFiles(sandbox);
  const registryDoc = await readYaml(registry);
  const servers = registryDoc.servers as Record<string, Record<string, unknown>>;
  assert.deepEqual(Object.keys(servers), ["localone", "remoteone"]);
  assert.equal(servers.localone?.type, "local");
  assert.deepEqual(servers.localone?.command, ["node", "server.js"]);
  assert.equal(servers.remoteone?.type, "remote");
  assert.equal(servers.remoteone?.url, "https://example.com/mcp");
  const providersDoc = await readYaml(providers);
  assert.deepEqual(providersDoc.defaults, { provider: "prov", model: "id" });
  assert.equal(await hashFile(userFile), userHash, "user global config must stay untouched");

  const registryHash = await hashFile(registry);
  const providersHash = await hashFile(providers);
  const second = await cli(sandbox, ["init"]);
  assert.equal(second.code, 0, second.stderr);
  assert.match(second.stdout, /mcp already in AgentHome: localone, remoteone/);
  assert.match(second.stdout, /model already in AgentHome: prov\/id/);
  assert.equal(await hashFile(registry), registryHash, "re-init must not rewrite registry.yaml");
  assert.equal(await hashFile(providers), providersHash, "re-init must not rewrite providers.yaml");
  assert.equal(await hashFile(userFile), userHash, "re-init must not touch the user config");
});

test("init notes a user project OpenCode config without touching it", async (t) => {
  const sandbox = await makeSandbox(t);
  const userJson = path.join(sandbox.project, "opencode.json");
  await fs.writeFile(userJson, '{\n  "model": "user/choice"\n}\n', "utf8");
  const userHash = await hashFile(userJson);

  const result = await cli(sandbox, ["init"]);
  assert.equal(result.code, 0, result.stderr);
  assert.match(result.stdout, /Note: project OpenCode config found/);
  assert.doesNotMatch(result.stdout, /First-installation adoption:/);
  assert.equal(await hashFile(userJson), userHash, "init must not touch the user project config");
});

test("isolation: full flow leaves the real OpenCode files untouched", async (t) => {
  const realBefore = await snapshotFiles(realOpenCodeFiles());
  const sandbox = await createSandbox();
  t.after(() => sandbox.cleanup());

  assert.equal((await cli(sandbox, ["init"])).code, 0);
  assert.equal((await cli(sandbox, ["apply", "opencode", "--scope", "project", "--dry-run"])).code, 0);
  assert.equal((await cli(sandbox, ["apply", "opencode", "--scope", "project"])).code, 0);
  assert.equal((await cli(sandbox, ["apply", "opencode", "--scope", "project"])).code, 0);
  assert.equal((await cli(sandbox, ["apply", "pi", "--scope", "project"])).code, 0);

  assert.deepEqual(await snapshotFiles(realOpenCodeFiles()), realBefore);
});

test("apply --dry-run plans the project opencode.jsonc without writing", async (t) => {
  const sandbox = await makeSandbox(t);
  await initSandbox(sandbox);
  const jsonc = path.join(sandbox.project, "opencode.jsonc");
  const json = path.join(sandbox.project, "opencode.json");
  const agents = path.join(sandbox.project, "AGENTS.md");

  const result = await cli(sandbox, ["apply", "opencode", "--scope", "project", "--dry-run"]);
  assert.equal(result.code, 0, result.stderr);
  assert.match(result.stdout, /Planned changes:/);
  assert.match(result.stdout, /opencode\.jsonc/);
  assert.equal(await hashFile(jsonc), null, "dry-run must not create opencode.jsonc");
  assert.equal(await hashFile(json), null, "dry-run must not create opencode.json");
  assert.equal(await hashFile(agents), null, "opencode apply must not create AGENTS.md");
});

test("apply opencode creates the managed project file with instructions and is idempotent", async (t) => {
  const sandbox = await makeSandbox(t);
  await initSandbox(sandbox);
  const jsonc = path.join(sandbox.project, "opencode.jsonc");
  const agents = path.join(sandbox.project, "AGENTS.md");

  const first = await cli(sandbox, ["apply", "opencode", "--scope", "project"]);
  assert.equal(first.code, 0, first.stderr);
  const content = await fs.readFile(jsonc, "utf8");
  const lines = content.split("\n");
  assert.equal(lines[0], MANAGED_HEADER[0]);
  assert.equal(lines[1], MANAGED_HEADER[1]);
  const parsed = await readJsonc(jsonc);
  assert.deepEqual(parsed.instructions, [".agenthome/rules.md", ".agenthome/memory.md"]);
  assert.equal(await hashFile(agents), null, "opencode must not create AGENTS.md");

  const hash = await hashFile(jsonc);
  const second = await cli(sandbox, ["apply", "opencode", "--scope", "project"]);
  assert.equal(second.code, 0, second.stderr);
  assert.match(second.stdout, /No changes/);
  assert.equal(await hashFile(jsonc), hash);
});

test("apply keeps a user opencode.json and creates a managed opencode.jsonc", async (t) => {
  const sandbox = await makeSandbox(t);
  await initSandbox(sandbox);
  const userJson = path.join(sandbox.project, "opencode.json");
  const agents = path.join(sandbox.project, "AGENTS.md");
  await fs.writeFile(
    userJson,
    `${JSON.stringify(
      {
        model: "user/model",
        mcp: {
          mine: { type: "remote", url: "https://example.com/mcp", enabled: true },
        },
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
  await fs.writeFile(agents, "# My own notes\n\nDo not lose this line.\n", "utf8");
  const jsonHash = await hashFile(userJson);
  const agentsHash = await hashFile(agents);

  const result = await cli(sandbox, ["apply", "opencode", "--scope", "project"]);
  assert.equal(result.code, 0, result.stderr);
  assert.equal(await hashFile(userJson), jsonHash, "user opencode.json must stay untouched");
  assert.equal(await hashFile(agents), agentsHash, "user AGENTS.md must stay untouched");

  const created = path.join(sandbox.project, "opencode.jsonc");
  await mustExist(created);
  assert.match(await fs.readFile(created, "utf8"), new RegExp(MANAGED_MARKER));
});

test("apply fails when the project opencode.jsonc belongs to the user, even with --force", async (t) => {
  const sandbox = await makeSandbox(t);
  await initSandbox(sandbox);
  const jsonc = path.join(sandbox.project, "opencode.jsonc");
  await fs.writeFile(jsonc, '// user comment\n{\n  "model": "user/choice"\n}\n', "utf8");
  const jsoncHash = await hashFile(jsonc);

  const blocked = await cli(sandbox, ["apply", "opencode", "--scope", "project"]);
  assert.notEqual(blocked.code, 0, "apply must fail when opencode.jsonc is user-owned");
  assert.match(blocked.stdout + blocked.stderr, /not managed by AgentHome/);
  assert.equal(await hashFile(jsonc), jsoncHash, "user opencode.jsonc must stay untouched");

  const forced = await cli(sandbox, ["apply", "opencode", "--scope", "project", "--force"]);
  assert.notEqual(forced.code, 0, "--force must not take over the user's opencode.jsonc");
  assert.equal(await hashFile(jsonc), jsoncHash, "user opencode.jsonc must stay untouched");
});

test("empty registry does not write an mcp key in the AgentHome file", async (t) => {
  const sandbox = await makeSandbox(t);
  await initSandbox(sandbox);
  const jsonc = path.join(sandbox.project, "opencode.jsonc");

  const result = await cli(sandbox, ["apply", "opencode", "--scope", "project"]);
  assert.equal(result.code, 0, result.stderr);
  const parsed = await readJsonc(jsonc);
  assert.equal(Object.prototype.hasOwnProperty.call(parsed, "mcp"), false, "mcp must be omitted");
  assert.equal(Object.prototype.hasOwnProperty.call(parsed, "model"), false, "model must be omitted");
  assert.deepEqual(parsed.instructions, [".agenthome/rules.md", ".agenthome/memory.md"]);
});

test("pi apply shares the project AGENTS.md block and skips .pi files without defaults or servers", async (t) => {
  const sandbox = await makeSandbox(t);
  await initSandbox(sandbox);
  const agents = path.join(sandbox.project, "AGENTS.md");

  const opencode = await cli(sandbox, ["apply", "opencode", "--scope", "project"]);
  assert.equal(opencode.code, 0, opencode.stderr);
  assert.equal(await hashFile(agents), null, "opencode must leave AGENTS.md to pi");

  const pi = await cli(sandbox, ["apply", "pi", "--scope", "project"]);
  assert.equal(pi.code, 0, pi.stderr);
  const content = await fs.readFile(agents, "utf8");
  assert.equal(count(content, PROJECT_START), 1);
  assert.equal(count(content, PROJECT_END), 1);
  assert.ok(content.indexOf(PROJECT_START) < content.indexOf(PROJECT_END));
  assert.equal(await hashFile(path.join(sandbox.project, ".pi", "settings.json")), null);
  assert.equal(await hashFile(path.join(sandbox.project, ".pi", "mcp.json")), null);
});
